### ISSUE TITLE
Ban 'N' residues from consensus residues in TRs?

### ISSUE THREAD

**Issue by SchwarzEM** [TravisWheelerLab/ULTRA#30]
I would like to scan the C. elegans genome for tandem repeats that have the following properties:

the TRs can range in period size up to 7,500 nt (with a argument of `-p 7500`), because I know there exist some tandem repeats that are almost as large (rRNA)

the TRs have no variation (i.e., no insertions, no deletions, and 100% identity to the consensus -- so, arguments of `-i 0 -d 0 -m 1`)

the TRs are banned from having 'N' in their consensus (so, given a choice between a small period size whose consensus is completely deterministic, or a large period size whose consensus is full of 'N' residues, ULTRA selects the deterministic short period size)

I can make ULTRA 1.0.0 (beta 1) do all of these things *except* ban 'N' residues in its allowed consensus.  Is there some argument I'm not aware of that would allow me to enforce this policy for an ULTRA run?

**Comment by SchwarzEM** [comment]
I should add that when I imposed the arguments `-i 0 -d 0 -m 1`, I very much expected that this alone would be sufficient yield completely deterministic consensus sequences for the TRs -- I was very surprised to see the longer TRs with longer repeat lengths show very extensive 'N' runs in their consensuses!

**Comment by DanielOlson** [comment]
The ‘N’ runs in consensus mean that the tandem repeat profile doesn’t have a strong enough consensus to label a specific nucleotide for that column. Right now we don’t have an argument to allow users to adjust how strong a consensus is needed for labeling (which I agree would be a useful feature). Your use case sounds interesting - I’d be happy to have a more in depth correspondance (I can be reached at daniel.olson at me com) to figure out if we can make ULTRA better for your usecase.

**Comment by DanielOlson** [comment]
Investigated ULTRA with -i 0 -d 0 -m 0 -p 7500 on C. elegans. Found a few things:

One, ULTRA (beta 5) is not using --minunits internally, resulting in some large period repeats having less than 2 full units of repeat (causing a bunch of Ns in the consensus sequence due to a large part of the consensus having no consensus at all).

Two, when using -m 1.0, ULTRA goes in and out of the repetitive state more frequently (any mutation will result in the the termination of a repetitive state). This causes ULTRA's Viterbi path to go in and out of the repeat states. ULTRA's repeat overlapping algorithm then sees these repeats and tries to join them, but none of the repeats have enough coverage to offer a good consensus (and also if the repeats are joined the -m 1.0 -i 0 -d 0 arguments will be broken).

I'll have the first issue fixed for ULTRA beta 6 (I expect sometime tomorrow)
I'll have the second issue partially fixed in ULTRA beta 6, but likely not fully fixed.

Many thanks for your usage / reporting!

**Comment by SchwarzEM** [comment]
Hi @DanielOlson,

First, thanks for your rapid response, and my apologies for my slow reply!  I was attending Biology of Genomes last week, and catching up on stuff when I got back this week.

Second, it sounds like you have already been able to do substantial debugging and that remaining issues aren't going to be practical to address right away; but, please let me know if there is other usage information you'd find helpful.  For instance, I could try rerunning my job with ULTRA beta 6 and let you know what differences I see...

**Comment by DanielOlson** [comment]
That shouldn't be necessary, but please let me know if you come across anything else that doesn't look quite right or if you have any additional comments/questions. Thanks once again!
